#!/bin/bash
docker run \
  --rm -it \
  --sig-proxy=true \
  --pid=host \
  -v "${PWD}":"/az" \
  -v $HOME/.netrc:/root/.netrc \
  -v $HOME/.azure:/root/.azure \
  -v /tmp/:/tmp/ \
  $extra_params \
  microsoft/azure-cli az "$@"
