#!/bin/bash
if ! type docker > /dev/null; then
  echo "Docker is required to be present on $PATH"
  exit 0
fi


docker run \
  --rm -it \
  --sig-proxy=true \
  --pid=host \
  --net=host \
  -v /tmp/:/tmp/ \
  -v $HOME/.gitconfig:/home/node/.gitconfig \
  -v $HOME/.npmrc:/home/node/.npmrc \
  -v $HOME/.netrc:/home/node/.netrc \
  -v "${PWD}":"/home/node/app" \
  -w "/home/node/app" \
  -u node \
  -p 8081:8081 \
  laurentgoderre/docker-tools:react-native npx react-native $@
