#!/bin/bash
docker run \
  --rm -it \
  --sig-proxy=true \
  --pid=host \
  -e SENTRY_DSN=$SENTRY_DSN \
  -v /tmp/:/tmp/ \
  -v $HOME/.gitconfig:/home/node/.gitconfig \
  -v $HOME/.netrc:/home/node/.netrc \
  -v "${PWD}":"/root" \
  $extra_params \
  getsentry/sentry-cli sentry-cli "$@"
