#!/bin/bash
docker run \
  --rm -it \
  --sig-proxy=true \
  --pid=host \
  -v "${PWD}":"/tf" \
  -v /tmp/:/tmp/ \
  -v $HOME/.netrc:/root/.netrc \
  -v $HOME/.azure:/root/.azure \
  -w "/tf" \
  $extra_params \
  hashicorp/terraform $@
