#!/bin/bash
if ! type docker > /dev/null; then
  echo "Docker is required to be present on $PATH"
  exit 0
fi

src="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo $src

docker run \
	--rm -it \
  -p 8000:80 \
  -v "${PWD}":"/usr/local/apache2/htdocs/" \
  -v "${src}/httpd-ssi.conf":"/usr/local/apache2/conf/httpd.conf" \
	-v /etc/hosts:/etc/hosts \
  --sig-proxy=true \
  --pid=host \
	laurentgoderre/docker-tools:ssi
