#!/bin/bash
# strict mode http://redsymbol.net/articles/unofficial-bash-strict-mode/
dockergrunt_promptchange=true
while getopts "n" opt "$@"; do
	case $opt in
		n )
      			dockergrunt_promptchange=false
      			;;
	esac
done

if [ ! -n "${ZSH_VERSION-}" ] ; then
	dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
else
	dir="$( cd "$( dirname "${(%):-%N}" )" && pwd )"
fi
project="${PWD##*/}"
bins=("node" "npm" "bower" "grunt" "http-server" "json-minify")

deactivate () {
	for bin in "${bins[@]}"
	do
		unalias "$bin"
	done

	if [ "$dockergrunt_promptchange" = true ]; then
		if ! [ -z "${_OLD_PS1+_}" ] ; then
		PS1="$_OLD_PS1"
		export PS1
		unset _OLD_PS1
	fi
    fi
}

if ( [ ! -n "${ZSH_VERSION-}" ] && [ "$(type -t npm)" == "alias" ] ) ||
	( [ -n "${ZSH_VERSION-}" ] && [ "$(type -w npm)" = "npm: alias" ] ); then
		echo "Already activated!"
else
	for bin in "${bins[@]}"
	do
		alias "$bin=$dir/$bin"
	done

	if [ "$dockergrunt_promptchange" = true ]; then
		_OLD_PS1="$PS1"
		PS1_APPEND="(Docker Node/Grunt/Bower)"
		if [ ! -n "${ZSH_VERSION-}" ] ; then
			PS1="\e[1;35m$PS1_APPEND\e[0m $PS1"
		else
			PS1="%F{magenta}$PS1_APPEND%F{white} $PS1"
		fi
	fi
fi
