#!/bin/sh
sc_port=4445

if (: "${SAUCE_PORT?}" ) 2>/dev/null ; then
	sc_port=$SAUCE_PORT
fi

if [ -n "$proxy_host" ]; then
	proxy_sett="--proxy $proxy_host \
	--proxy-userpwd $proxy_auth \
	--proxy-tunnel"
fi

docker run \
	--rm -it \
	--network="host" \
	-p $sc_port:$sc_port \
	-e SAUCE_USERNAME=$SAUCE_USERNAME \
	-e SAUCE_ACCESS_KEY=$SAUCE_ACCESS_KEY \
	-e NO_PROXY="$NO_PROXY" \
	-v /etc/hosts:/etc/hosts \
	ustwo/sauce-connect \
		--se-port $sc_port \
		$proxy_sett
